/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 christmas.glb 
Author: Tatsi (https://sketchfab.com/Tatsi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/christmas-pumpkin-32fb9ea0361b4cac89d1cc756d888b38
Title: Christmas Pumpkin
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Christmas(props) {
  const { nodes, materials } = useGLTF("/christmas.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[21.288, 92.206, 54.493]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          geometry={nodes.leaf3_Alpha_0.geometry}
          material={materials.Alpha}
          position={[1.277, -3.296, -14.489]}
        />
        <mesh
          geometry={nodes.leaf1_Alpha_0.geometry}
          material={materials.Alpha}
          position={[4.072, -3.457, -13.49]}
        />
        <mesh
          geometry={nodes.leaf2_Alpha_0.geometry}
          material={materials.Alpha}
          position={[0.642, 4.247, -7.577]}
        />
        <mesh
          geometry={nodes.leaf4_Alpha_0.geometry}
          material={materials.Alpha}
          position={[1.643, -9.598, -2.219]}
        />
        <mesh
          geometry={nodes.Amelia001_Alpha_0.geometry}
          material={materials.Alpha}
          position={[8.596, 19.465, 27.739]}
        />
        <mesh
          geometry={nodes.Amelia002_Alpha_0.geometry}
          material={materials.Alpha}
          position={[6.749, 12.709, 30.821]}
        />
        <mesh
          geometry={nodes.Amelia003_Alpha_0.geometry}
          material={materials.Alpha}
          position={[11.38, 11.599, 27.995]}
        />
        <mesh
          geometry={nodes.Rope001_Alpha_0.geometry}
          material={materials.Alpha}
          position={[9.238, 15.808, 24.649]}
        />
        <mesh
          geometry={nodes.Rope_Alpha_0.geometry}
          material={materials.Alpha}
          position={[-128.892, -115.59, 64.961]}
        />
        <mesh
          geometry={nodes.Fur2_Alpha_0.geometry}
          material={materials.Alpha}
          position={[31.006, -114.022, -35.651]}
        />
        <mesh
          geometry={nodes.Fur1_Alpha_0.geometry}
          material={materials.Alpha}
          position={[30.952, -114.004, -35.639]}
        />
        <mesh
          geometry={nodes.Fur3_Alpha_0.geometry}
          material={materials.Alpha}
          position={[37.127, -119.286, -39.7]}
        />
        <mesh
          geometry={nodes.Fur4_Alpha_0.geometry}
          material={materials.Alpha}
          position={[34.945, -121.611, -40.616]}
        />
        <mesh
          geometry={nodes.PlaneFur3_Alpha_0.geometry}
          material={materials.Alpha}
          position={[44.814, -122.034, -51.545]}
          rotation={[0, 0, 0.262]}
        />
        <mesh
          geometry={nodes.PlaneFur2_Alpha_0.geometry}
          material={materials.Alpha}
          position={[44.814, -122.034, -51.545]}
        />
        <mesh
          geometry={nodes.PlaneFur1_Alpha_0.geometry}
          material={materials.Alpha}
          position={[44.814, -122.034, -51.545]}
          rotation={[0, -0.262, 0]}
        />
        <mesh
          geometry={nodes.leaf005_Alpha_0.geometry}
          material={materials.Alpha}
          position={[27.286, -9.598, -2.219]}
        />
        <mesh
          geometry={nodes.Eyes_Alpha_0.geometry}
          material={materials.Alpha}
          position={[40.741, -104.948, -24.205]}
        />
        <mesh
          geometry={nodes.Plane003_Alpha_0.geometry}
          material={materials.Alpha}
          position={[36.358, -102.414, -21.425]}
        />
        <mesh
          geometry={nodes.Plane002_Alpha_0.geometry}
          material={materials.Alpha}
          position={[36.76, -103.397, -21.988]}
        />
      </group>
      <group
        position={[-56.11, 188.623, -48.978]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
      >
        <group position={[108.099, 20.068, -95.396]}>
          <mesh
            geometry={nodes.Led_Translucent_0.geometry}
            material={materials.Translucent}
            position={[0.317, 1.649, 1.577]}
          />
        </group>
        <mesh
          geometry={nodes.Sphere013_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-25.421, -38.193, -20.534]}
        />
        <mesh
          geometry={nodes.Sphere014_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-25.421, -38.193, -12.595]}
        />
        <mesh
          geometry={nodes.Sphere015_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-25.421, -38.193, 10.041]}
        />
        <mesh
          geometry={nodes.Sphere016_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-25.421, -38.193, 21.133]}
        />
        <mesh
          geometry={nodes.Window_Translucent_0.geometry}
          material={materials.Translucent}
          position={[17.64, 30.793, -9.523]}
          rotation={[0, 0, -0.087]}
        />
        <mesh
          geometry={nodes.Icicle_Translucent_0.geometry}
          material={materials.Translucent}
          position={[122.804, 51.584, -67.492]}
        />
        <mesh
          geometry={nodes.Icicle001_Translucent_0.geometry}
          material={materials.Translucent}
          position={[119.086, 67.144, -56.504]}
        />
        <mesh
          geometry={nodes.Icicle003_Translucent_0.geometry}
          material={materials.Translucent}
          position={[121.041, 46.887, -81.336]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Icicle004_Translucent_0.geometry}
          material={materials.Translucent}
          position={[121.633, 54.984, -64.678]}
        />
        <mesh
          geometry={nodes.Icicle006_Translucent_0.geometry}
          material={materials.Translucent}
          position={[71.459, 140.825, -108.272]}
        />
        <mesh
          geometry={nodes.Icicle007_Translucent_0.geometry}
          material={materials.Translucent}
          position={[116.14, 24.695, -99.717]}
        />
        <mesh
          geometry={nodes.Icicle008_Translucent_0.geometry}
          material={materials.Translucent}
          position={[56.691, 149.08, -107.751]}
        />
        <mesh
          geometry={nodes.icicle008_Translucent_0.geometry}
          material={materials.Translucent}
          position={[41.691, -55.173, -109.066]}
        />
        <mesh
          geometry={nodes.Icicle009_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-66.134, 108.958, -100.494]}
        />
        <mesh
          geometry={nodes.Icicle010_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-67.596, 105.673, -97.68]}
        />
        <mesh
          geometry={nodes.Icicle011_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-60.208, 115.61, -103.006]}
        />
        <mesh
          geometry={nodes.Icicle012_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-75.894, 59.84, -100.311]}
        />
        <mesh
          geometry={nodes.icicle012_Translucent_0.geometry}
          material={materials.Translucent}
          position={[117.076, 11.414, -111.536]}
        />
        <mesh
          geometry={nodes.Icicle013_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-36.535, 107.284, -137.748]}
        />
        <mesh
          geometry={nodes.Icicle014_Translucent_0.geometry}
          material={materials.Translucent}
          position={[126.791, 43.609, -92.991]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Icicle017_Translucent_0.geometry}
          material={materials.Translucent}
          position={[113.352, 27.698, -97.861]}
        />
        <mesh
          geometry={nodes.icicle021_Translucent_0.geometry}
          material={materials.Translucent}
          position={[88.091, -28.356, -131.107]}
        />
        <mesh
          geometry={nodes.icicle022_Translucent_0.geometry}
          material={materials.Translucent}
          position={[81.01, -35.862, -129.619]}
        />
        <mesh
          geometry={nodes.icicle023_Translucent_0.geometry}
          material={materials.Translucent}
          position={[78.019, -39.219, -128.202]}
        />
        <mesh
          geometry={nodes.icicle024_Translucent_0.geometry}
          material={materials.Translucent}
          position={[112.625, 7.676, -106.042]}
        />
        <mesh
          geometry={nodes.icicle025_Translucent_0.geometry}
          material={materials.Translucent}
          position={[42.16, 28.951, 5.081]}
        />
        <mesh
          geometry={nodes.icicle026_Translucent_0.geometry}
          material={materials.Translucent}
          position={[40.262, 36.066, 10.155]}
        />
        <mesh
          geometry={nodes.icicle027_Translucent_0.geometry}
          material={materials.Translucent}
          position={[44.951, 153.482, -107.273]}
        />
        <mesh
          geometry={nodes.icicle028_Translucent_0.geometry}
          material={materials.Translucent}
          position={[24.01, -58.305, -113.439]}
        />
        <mesh
          geometry={nodes.icicle029_Translucent_0.geometry}
          material={materials.Translucent}
          position={[8.871, -56.705, -115.261]}
        />
        <mesh
          geometry={nodes.icicle030_Translucent_0.geometry}
          material={materials.Translucent}
          position={[30.318, -58.026, -112.263]}
        />
        <mesh
          geometry={nodes.icicle031_Translucent_0.geometry}
          material={materials.Translucent}
          position={[91.538, -24.964, -126.992]}
        />
        <mesh
          geometry={nodes.icicle032_Translucent_0.geometry}
          material={materials.Translucent}
          position={[76.261, 135.576, -102.748]}
        />
        <mesh
          geometry={nodes.icicle033_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-40.134, 102.839, -137.523]}
        />
        <mesh
          geometry={nodes.icicle034_Translucent_0.geometry}
          material={materials.Translucent}
          position={[36.702, 39.128, 7.807]}
        />
        <mesh
          geometry={nodes.Led_L_Translucent_0.geometry}
          material={materials.Translucent}
          position={[115.063, 40.801, -66.366]}
        />
        <mesh
          geometry={nodes.Led001_Translucent_0.geometry}
          material={materials.Translucent}
          position={[92.41, -21.228, -122.273]}
        />
        <mesh
          geometry={nodes.Sphere005_Translucent_0.geometry}
          material={materials.Translucent}
          position={[112.897, 93.296, -58.495]}
        />
        <mesh
          geometry={nodes.Sphere006_Translucent_0.geometry}
          material={materials.Translucent}
          position={[112.897, 93.296, -54.966]}
        />
        <mesh
          geometry={nodes.Steklo2_Translucent_0.geometry}
          material={materials.Translucent}
          position={[67.232, -9.847, -94.806]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Steklo3_Translucent_0.geometry}
          material={materials.Translucent}
          position={[81.917, 4.572, -95.692]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Steklo004_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-23.057, 83.196, -111.255]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Steklo005_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-33.626, 71.126, -111.256]}
          rotation={[0, 0, Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Led002_Translucent_0.geometry}
          material={materials.Translucent}
          position={[-47.277, 90.431, -128.075]}
          rotation={[0, 0, -2.985]}
        />
      </group>
      <group
        position={[6.528, 122.869, 26.819]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group
          position={[-15.317, 45.261, 42.342]}
          rotation={[0, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes.Snow_L_Base_0.geometry}
            material={materials.Base}
            position={[-44.825, 15.539, -22.283]}
          />
        </group>
        <mesh
          geometry={nodes.Tail_L_Base_0.geometry}
          material={materials.Base}
          position={[0.222, 90.087, 20.059]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.pumpkin_L_Base_0.geometry}
          material={materials.Base}
          position={[-22.231, 47.6, -1.397]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StonesD_L_Base_0.geometry}
          material={materials.Base}
          position={[0.222, 90.087, 20.059]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StonesC_L_Base_0.geometry}
          material={materials.Base}
          position={[0.222, 90.087, 20.059]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StonesB_L_Base_0.geometry}
          material={materials.Base}
          position={[0.222, 90.087, 20.059]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.StonesA_L_Base_0.geometry}
          material={materials.Base}
          position={[0.222, 90.087, 20.059]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Ground_L_Base_0.geometry}
          material={materials.Base}
          position={[0, 0, -94.15]}
          rotation={[0, 0, -Math.PI / 2]}
        />
      </group>
      <group
        position={[6.294, 111.236, 15.683]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group position={[20.793, 87.718, -33.868]} rotation={[0, 0, -1.396]}>
          <mesh
            geometry={nodes.casement_window3_Details_0.geometry}
            material={materials.Details}
            position={[-0.002, 0.028, 0]}
          />
        </group>
        <group
          position={[-38.893, -51.868, -24.525]}
          rotation={[-1.036, 0.203, 1.47]}
        >
          <mesh
            geometry={nodes.Krysha_Details_0.geometry}
            material={materials.Details}
            position={[-0.405, -40.742, -7.33]}
          />
        </group>
        <group
          position={[-73.814, -89.964, -70.373]}
          rotation={[0, 0, -1.518]}
          scale={1.058}
        >
          <mesh
            geometry={nodes.Zai1_Details_0.geometry}
            material={materials.Details}
            position={[-169.263, 77.07, 100.932]}
          />
        </group>
        <group
          position={[-92.713, -74.621, -50.545]}
          rotation={[0, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes.wing1_Details_0.geometry}
            material={materials.Details}
            position={[0.424, 10.515, -2.38]}
          />
        </group>
        <group
          position={[-83.111, -74.621, -50.545]}
          rotation={[0, 0, -Math.PI / 2]}
        >
          <mesh
            geometry={nodes.wing2_Details_0.geometry}
            material={materials.Details}
            position={[0.424, 0.914, -2.38]}
          />
        </group>
        <mesh
          geometry={nodes.Bant_Details_0.geometry}
          material={materials.Details}
          position={[14.192, -38.832, -7.877]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Bant001_Details_0.geometry}
          material={materials.Details}
          position={[9.642, -41.308, -6.139]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Bant002_Details_0.geometry}
          material={materials.Details}
          position={[18.837, -37.37, -5.67]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Bant002_Details_0_1.geometry}
          material={materials.Details}
          position={[11.86, -39.653, -15.669]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Bant003_Details_0.geometry}
          material={materials.Details}
          position={[17.748, -38.157, -15.182]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.casement_window4_Details_0.geometry}
          material={materials.Details}
          position={[20.605, 89.067, -27.077]}
          rotation={[0, 0, -1.396]}
        />
        <mesh
          geometry={nodes.casement_window5_Details_0.geometry}
          material={materials.Details}
          position={[9.54, 97.347, -27.233]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.casement_window6_Details_0.geometry}
          material={materials.Details}
          position={[-73.271, -16.169, -46.531]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.casement_window010_Details_0.geometry}
          material={materials.Details}
          position={[8.722, 98.287, -33.87]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.casement_window011_Details_0.geometry}
          material={materials.Details}
          position={[19.317, 99.113, -52.257]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.casement_window012_Details_0.geometry}
          material={materials.Details}
          position={[-73.17, -0.634, -28.553]}
          rotation={[0, 0, -1.396]}
        />
        <mesh
          geometry={nodes.casement_window013_Details_0.geometry}
          material={materials.Details}
          position={[-72.079, -0.283, -21.762]}
          rotation={[0, 0, -1.396]}
        />
        <mesh
          geometry={nodes.casement_window014_Details_0.geometry}
          material={materials.Details}
          position={[-56.459, -17.787, -28.554]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.casement_window015_Details_0.geometry}
          material={materials.Details}
          position={[-56.101, -16.579, -21.757]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Dver_Details_0.geometry}
          material={materials.Details}
          position={[10.459, -34.311, -2.285]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Dver_Details_0_1.geometry}
          material={materials.Details}
          position={[12.995, -41.415, -2.382]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.hat003_Details_0.geometry}
          material={materials.Details}
          position={[-100.229, -72.167, -58.056]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha4_Details_0.geometry}
          material={materials.Details}
          position={[-54.975, -29.656, -8.266]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha5_Details_0.geometry}
          material={materials.Details}
          position={[37.624, -27.148, 17.498]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha6_Details_0.geometry}
          material={materials.Details}
          position={[46.883, -21.503, 4.001]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha007_Details_0.geometry}
          material={materials.Details}
          position={[-85.532, 9.976, -13.418]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha8_Details_0.geometry}
          material={materials.Details}
          position={[50.497, -18.137, -9.867]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha9_Details_0.geometry}
          material={materials.Details}
          position={[-4.112, -35.057, 26.662]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha10_Details_0.geometry}
          material={materials.Details}
          position={[-17.844, -38.374, 17.731]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha11_Details_0.geometry}
          material={materials.Details}
          position={[-31.628, -34.556, -8.982]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha093_Details_0.geometry}
          material={materials.Details}
          position={[-46.662, -34.522, -14.584]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha095_Details_0.geometry}
          material={materials.Details}
          position={[-86.059, -4.684, -6.758]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha096_Details_0.geometry}
          material={materials.Details}
          position={[-65.167, -26.756, -3.691]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha098_Details_0.geometry}
          material={materials.Details}
          position={[40.631, 4.102, -15.178]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha099_Details_0.geometry}
          material={materials.Details}
          position={[53.527, 22.469, -14.478]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha100_Details_0.geometry}
          material={materials.Details}
          position={[59.478, 35.788, -14.725]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha101_Details_0.geometry}
          material={materials.Details}
          position={[57.855, 51.795, -12.979]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha102_Details_0.geometry}
          material={materials.Details}
          position={[56.078, 65.695, -11.579]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha103_Details_0.geometry}
          material={materials.Details}
          position={[46.596, 76.972, -8.736]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha104_Details_0.geometry}
          material={materials.Details}
          position={[43.743, 90.631, -7.688]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha105_Details_0.geometry}
          material={materials.Details}
          position={[31.319, 98.733, -6.081]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha106_Details_0.geometry}
          material={materials.Details}
          position={[-76.098, -16.65, -2.074]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha107_Details_0.geometry}
          material={materials.Details}
          position={[19.622, 107.882, -5.964]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha107_Details_0_1.geometry}
          material={materials.Details}
          position={[-48.458, 37.791, 81.228]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha108_Details_0.geometry}
          material={materials.Details}
          position={[-3.035, 106.039, -6.828]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha109_Details_0.geometry}
          material={materials.Details}
          position={[-17.457, 115.107, -13.075]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha110_Details_0.geometry}
          material={materials.Details}
          position={[-29.053, 101.457, -12.2]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha111_Details_0.geometry}
          material={materials.Details}
          position={[-44.746, 101.896, -14.164]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha112_Details_0.geometry}
          material={materials.Details}
          position={[-67.704, 79.19, -12.461]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha113_Details_0.geometry}
          material={materials.Details}
          position={[-79.235, 70.877, -12.904]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha114_Details_0.geometry}
          material={materials.Details}
          position={[-82.467, 59.012, -15.586]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha115_Details_0.geometry}
          material={materials.Details}
          position={[11.229, -32.927, 29.101]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha116_Details_0.geometry}
          material={materials.Details}
          position={[22.169, -20.175, 25.175]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha117_Details_0.geometry}
          material={materials.Details}
          position={[-26.77, -31.127, 2.559]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha118_Details_0.geometry}
          material={materials.Details}
          position={[-86.018, 43.573, -17.398]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha119_Details_0.geometry}
          material={materials.Details}
          position={[-83.744, 31.158, -19.417]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha120_Details_0.geometry}
          material={materials.Details}
          position={[-51.65, 84.278, -12.461]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha121_Details_0.geometry}
          material={materials.Details}
          position={[-12.89, 68.23, 70.821]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha122_Details_0.geometry}
          material={materials.Details}
          position={[-15.197, 66.034, 79.279]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha123_Details_0.geometry}
          material={materials.Details}
          position={[-19.76, 59.762, 87.329]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha124_Details_0.geometry}
          material={materials.Details}
          position={[-19.211, 35.361, 99.08]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha125_Details_0.geometry}
          material={materials.Details}
          position={[-51.975, 31.988, 70.802]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Krysha126_Details_0.geometry}
          material={materials.Details}
          position={[-38.457, 46.308, 90.199]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Okno_Details_0.geometry}
          material={materials.Details}
          position={[-74.107, -19.776, -11.361]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Okno_verh2_Details_0.geometry}
          material={materials.Details}
          position={[-32.087, 47.953, 66.813]}
          rotation={[0, 0, -1.658]}
        />
        <mesh
          geometry={nodes.Okno002_Details_0.geometry}
          material={materials.Details}
          position={[20.07, 100.593, -17.087]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Porog1_Details_0.geometry}
          material={materials.Details}
          position={[11.483, -37.485, -61.779]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar009_Details_0.geometry}
          material={materials.Details}
          position={[75.864, -85.685, -55.786]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar010_Details_0.geometry}
          material={materials.Details}
          position={[86.098, -88.567, -74.814]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar011_Details_0.geometry}
          material={materials.Details}
          position={[89.085, -84.569, -65.61]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar012_Details_0.geometry}
          material={materials.Details}
          position={[92.787, -86.101, -74.433]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar013_Details_0.geometry}
          material={materials.Details}
          position={[99.494, -88.126, -74.169]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar014_Details_0.geometry}
          material={materials.Details}
          position={[103.124, -95.91, -27.513]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar016_Details_0.geometry}
          material={materials.Details}
          position={[102.191, -93.222, -40.592]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar017_Details_0.geometry}
          material={materials.Details}
          position={[77.451, -94.574, -62.042]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar018_Details_0.geometry}
          material={materials.Details}
          position={[75.283, -92.981, -60.258]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar019_Details_0.geometry}
          material={materials.Details}
          position={[92.242, 74.842, -79.638]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar020_Details_0.geometry}
          material={materials.Details}
          position={[90, 75.832, -76.298]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar021_Details_0.geometry}
          material={materials.Details}
          position={[91.281, -100.041, -31.566]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar022_Details_0.geometry}
          material={materials.Details}
          position={[96.435, -93.032, -75.162]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar024_Details_0.geometry}
          material={materials.Details}
          position={[96.824, -71.287, -53.366]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar025_Details_0.geometry}
          material={materials.Details}
          position={[93.656, -87.558, -52.318]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar027_Details_0.geometry}
          material={materials.Details}
          position={[110.643, -88.081, -55.943]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar028_Details_0.geometry}
          material={materials.Details}
          position={[104.832, -87.377, -50.755]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar031_Details_0.geometry}
          material={materials.Details}
          position={[106.172, -97.519, -76.863]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar032_Details_0.geometry}
          material={materials.Details}
          position={[81.923, -96.449, -75.678]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar035_Details_0.geometry}
          material={materials.Details}
          position={[38.545, -148.708, -102.338]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar038_Details_0.geometry}
          material={materials.Details}
          position={[137.586, -24.207, -73.863]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar040_Details_0.geometry}
          material={materials.Details}
          position={[45.604, -147.934, -98.425]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar041_Details_0.geometry}
          material={materials.Details}
          position={[45.132, -145.72, -82.581]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar043_Details_0.geometry}
          material={materials.Details}
          position={[133.608, -29.046, -68.615]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar047_Details_0.geometry}
          material={materials.Details}
          position={[83.53, -80.53, -70.064]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar049_Details_0.geometry}
          material={materials.Details}
          position={[84.278, 85.759, -86.381]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar051_Details_0.geometry}
          material={materials.Details}
          position={[85.864, 85.23, -86.605]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar053_Details_0.geometry}
          material={materials.Details}
          position={[-125.114, 29.973, -85.68]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar055_Details_0.geometry}
          material={materials.Details}
          position={[-59.817, 127.078, -82.783]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar062_Details_0.geometry}
          material={materials.Details}
          position={[-115.587, 47.737, -75.836]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar065_Details_0.geometry}
          material={materials.Details}
          position={[-115.651, 43.601, -77.366]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar070_Details_0.geometry}
          material={materials.Details}
          position={[-125.92, 19.468, -87.391]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar072_Details_0.geometry}
          material={materials.Details}
          position={[-125.583, 40.758, -84.726]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar073_Details_0.geometry}
          material={materials.Details}
          position={[-49.257, 131.744, -81.277]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar075_Details_0.geometry}
          material={materials.Details}
          position={[-53.236, 126.905, -76.028]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Vetkar077_Details_0.geometry}
          material={materials.Details}
          position={[-121.316, 29.469, -81.828]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Cake3_Details_0.geometry}
          material={materials.Details}
          position={[-73.934, -18.595, -33.264]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Dver_Details_0_2.geometry}
          material={materials.Details}
          position={[10.568, -37.553, 10.996]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.globe_Details_0.geometry}
          material={materials.Details}
          position={[24.319, -37.2, -14.156]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.globe001_Details_0.geometry}
          material={materials.Details}
          position={[23.582, -36.076, -24.049]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.globe002_Details_0.geometry}
          material={materials.Details}
          position={[14.971, -41.842, -28.925]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.globe003_Details_0.geometry}
          material={materials.Details}
          position={[2.157, -43.775, -19.587]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.globe004_Details_0.geometry}
          material={materials.Details}
          position={[6.884, -41.671, -27.215]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.globe005_Details_0.geometry}
          material={materials.Details}
          position={[5.734, -43.927, -12.371]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.handle1_Details_0.geometry}
          material={materials.Details}
          position={[3.319, -41.243, -38.672]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.handle10_Details_0.geometry}
          material={materials.Details}
          position={[3.319, -41.243, -35.042]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.handle13_Details_0.geometry}
          material={materials.Details}
          position={[2.184, -38.124, -35.042]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Konfeta1_Details_0.geometry}
          material={materials.Details}
          position={[87.802, -88.427, -33.731]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Konfeta003_Details_0.geometry}
          material={materials.Details}
          position={[79.231, -90.205, -47.747]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Konfeta004_Details_0.geometry}
          material={materials.Details}
          position={[100.626, -103.218, -55.272]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Moon_Details_0.geometry}
          material={materials.Details}
          position={[-99.017, 90.505, 34.05]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.snowman_Details_0.geometry}
          material={materials.Details}
          position={[98.673, -86.409, -47.872]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere002_Details_0.geometry}
          material={materials.Details}
          position={[29.635, -49.458, 15.39]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere003_Details_0.geometry}
          material={materials.Details}
          position={[31.768, -49.458, 16.406]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere004_Details_0.geometry}
          material={materials.Details}
          position={[30.893, -49.458, 13.137]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere008_Details_0.geometry}
          material={materials.Details}
          position={[-79.902, -21.161, -26.361]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere010_Details_0.geometry}
          material={materials.Details}
          position={[-77.576, -13.141, -26.661]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere011_Details_0.geometry}
          material={materials.Details}
          position={[-75.307, -13.804, -26.109]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere012_Details_0.geometry}
          material={materials.Details}
          position={[-71.56, -12.769, -26.346]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere017_Details_0.geometry}
          material={materials.Details}
          position={[-80.303, -17.58, -26.793]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere018_Details_0.geometry}
          material={materials.Details}
          position={[-77.831, -21.135, -26.246]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere019_Details_0.geometry}
          material={materials.Details}
          position={[-76.898, -24.689, -26.745]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere020_Details_0.geometry}
          material={materials.Details}
          position={[-74.608, -24.935, -26.745]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere021_Details_0.geometry}
          material={materials.Details}
          position={[-73.069, -22.88, -26.302]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere022_Details_0.geometry}
          material={materials.Details}
          position={[-70.729, -24.427, -26.19]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere023_Details_0.geometry}
          material={materials.Details}
          position={[-68.839, -17.775, -26.213]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere024_Details_0.geometry}
          material={materials.Details}
          position={[-80.246, -22.911, -27.514]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Sphere025_Details_0.geometry}
          material={materials.Details}
          position={[-78.514, -23.219, -26.975]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Tarelka2_Details_0.geometry}
          material={materials.Details}
          position={[-73.934, -18.595, -42.762]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Zai2_Details_0.geometry}
          material={materials.Details}
          position={[-93.247, -71.985, -72.535]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.bell2_Details_0.geometry}
          material={materials.Details}
          position={[30.802, -48.545, -8.839]}
        />
        <mesh
          geometry={nodes.bell1_Details_0.geometry}
          material={materials.Details}
          position={[30.802, -48.545, -7.123]}
        />
        <mesh
          geometry={nodes.bell_Details_0.geometry}
          material={materials.Details}
          position={[30.802, -48.545, 7.352]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Torus008_Details_0.geometry}
          material={materials.Details}
          position={[-99.318, -70.217, -55.171]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.horn1_Details_0.geometry}
          material={materials.Details}
          position={[-90.584, -76.201, -41.653]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.horn2_Details_0.geometry}
          material={materials.Details}
          position={[-85.511, -75.846, -41.653]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Pero1_Details_0.geometry}
          material={materials.Details}
          position={[-88.011, -76.284, -47.247]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Pero002_Details_0.geometry}
          material={materials.Details}
          position={[-88.011, -76.284, -47.247]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Pero003_Details_0.geometry}
          material={materials.Details}
          position={[-88.011, -76.284, -47.247]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Pero004_Details_0.geometry}
          material={materials.Details}
          position={[-88.011, -76.284, -47.247]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Pero005_Details_0.geometry}
          material={materials.Details}
          position={[-88.011, -76.284, -47.247]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Pero006_Details_0.geometry}
          material={materials.Details}
          position={[-88.011, -76.284, -47.247]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Pero007_Details_0.geometry}
          material={materials.Details}
          position={[-88.011, -76.284, -47.247]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Pero008_Details_0.geometry}
          material={materials.Details}
          position={[-88.011, -76.284, -47.247]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Snegir_Details_0.geometry}
          material={materials.Details}
          position={[-88.01, -76.284, -50.005]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Snegir_Details_0_1.geometry}
          material={materials.Details}
          position={[-88.01, -76.284, -44.793]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.beak_Details_0.geometry}
          material={materials.Details}
          position={[-87.783, -79.933, -44.255]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Tail004_Details_0.geometry}
          material={materials.Details}
          position={[-86.692, -70.151, -52.006]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Tail005_Details_0.geometry}
          material={materials.Details}
          position={[-88.257, -68.616, -51.947]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          geometry={nodes.Tail006_Details_0.geometry}
          material={materials.Details}
          position={[-89.782, -69.992, -51.99]}
          rotation={[0, 0, -Math.PI / 2]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/christmas.glb");
