/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 new.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function New(props) {
  const { nodes, materials } = useGLTF("./public/new.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
        position={[0, 2, 0]}
        rotation={[Math.PI / 2, 28, 0]}
        scale={20.801}
      />
      <mesh
        geometry={nodes.mesh_1.geometry}
        material={nodes.mesh_1.material}
        position={[0, 2, 0]}
        rotation={[0, 0.331, 0]}
        scale={20.554}
      />
      <mesh
        geometry={nodes.mesh_2.geometry}
        material={nodes.mesh_2.material}
        position={[0, 2, 0]}
        rotation={[Math.PI / 2, 28, 0]}
        scale={[49.879, 35.373, 29.745]}
      />
      <mesh
        geometry={nodes.mesh_3.geometry}
        material={nodes.mesh_3.material}
        position={[0, 2, 1.407]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[31.318, 22.21, 18.676]}
      />
    </group>
  );
}

useGLTF.preload("./public/new.glb");
