/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Adipriatna (https://sketchfab.com/adipriatna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dyton-bike-62bf8ec7430c45a98ed355b80345f607
Title: Dyton Bike
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Scene(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.299}>
          <group name="Root">
            <group name="Camera" position={[-7.933, 3.689, 2.041]} rotation={[1.304, -0.632, -0.171]} />
            <group name="Cylinder000" position={[-1.428, 10.716, 0.054]} rotation={[0, 1.57, 0]} scale={[0.002, 0.002, 0.017]}>
              <mesh name="Cylinder000_0" geometry={nodes.Cylinder000_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Torus001" position={[-1.831, 10.793, 1.398]} rotation={[0, 0.129, 0]} scale={0.023}>
              <mesh name="Torus001_0" geometry={nodes.Torus001_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Torus" position={[-1.834, 10.615, 1.398]} rotation={[0, 0.129, 0]} scale={0.023}>
              <mesh name="Torus_0" geometry={nodes.Torus_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="rangka_utama_spedah" position={[-1.533, 10.686, 0.521]} rotation={[-Math.PI / 2, 0, -0.024]} scale={0.756}>
              <mesh name="rangka_utama_spedah_0" geometry={nodes.rangka_utama_spedah_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Plane002" position={[-2.037, 10.71, 0.624]} rotation={[0, -0.726, 0]} scale={0.044}>
              <mesh name="Plane002_0" geometry={nodes.Plane002_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Plane001" position={[-4.017, 10.71, 0.825]} rotation={[0, -0.024, 0]} scale={0.045}>
              <mesh name="Plane001_0" geometry={nodes.Plane001_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="kotak_ajah" position={[-3.321, 10.719, 1.496]} rotation={[Math.PI, -0.541, 0]} scale={[-0.054, 0.054, 0.054]}>
              <mesh name="kotak_ajah_0" geometry={nodes.kotak_ajah_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="kayuh_spedah" position={[-2.434, 10.641, 0.022]} rotation={[0, -0.024, 0]} scale={[0.012, 0.022, 0.022]}>
              <mesh name="kayuh_spedah_0" geometry={nodes.kayuh_spedah_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="jok_Pilot" position={[-3.474, 10.638, 0.777]} rotation={[0, 0.383, 0]} scale={0.04}>
              <mesh name="jok_Pilot_0" geometry={nodes.jok_Pilot_0.geometry} material={materials['Material.002']} />
            </group>
            <group name="Gear004" position={[-2.43, 10.801, 0.023]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.191, 0.191, 0.089]}>
              <mesh name="Gear004_0" geometry={nodes.Gear004_0.geometry} material={materials.Root} />
            </group>
            <group name="Gear003" position={[-1.429, 10.63, 0.11]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.029, 0.029, 0.008]}>
              <mesh name="Gear003_0" geometry={nodes.Gear003_0.geometry} material={materials.Root} />
            </group>
            <group name="Gear002" position={[-1.429, 10.635, 0.11]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.035, 0.035, 0.009]}>
              <mesh name="Gear002_0" geometry={nodes.Gear002_0.geometry} material={materials.Root} />
            </group>
            <group name="Gear001" position={[-1.429, 10.64, 0.11]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.046, 0.046, 0.012]}>
              <mesh name="Gear001_0" geometry={nodes.Gear001_0.geometry} material={materials.Root} />
            </group>
            <group name="Gear" position={[-1.429, 10.646, 0.11]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.052, 0.052, 0.024]}>
              <mesh name="Gear_0" geometry={nodes.Gear_0.geometry} material={materials.Root} />
            </group>
            <group name="Cylinder009" position={[-1.428, 10.717, 0.11]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.022, 0.022, 0.087]}>
              <mesh name="Cylinder009_0" geometry={nodes.Cylinder009_0.geometry} material={materials.Root} />
            </group>
            <group name="Cylinder008" position={[-1.04, 10.711, 0.815]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.008, 0.008, 0.063]}>
              <mesh name="Cylinder008_0" geometry={nodes.Cylinder008_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cylinder006" position={[-3.882, 10.712, -0.639]} rotation={[0, -0.024, 0]} scale={0.011}>
              <mesh name="Cylinder006_0" geometry={nodes.Cylinder006_0.geometry} material={materials.Root} />
            </group>
            <group name="Cylinder005" position={[-1.968, 10.717, 1.379]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.029, 0.029, 0.036]}>
              <mesh name="Cylinder005_0" geometry={nodes.Cylinder005_0.geometry} material={materials.Root} />
            </group>
            <group name="Cylinder004" position={[-3.474, 10.638, 0.777]} rotation={[0, 0.383, 0]} scale={0.04}>
              <mesh name="Cylinder004_0" geometry={nodes.Cylinder004_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Cylinder003" position={[-1.413, 10.712, -0.566]} rotation={[0, -0.024, 0]} scale={0.011}>
              <mesh name="Cylinder003_0" geometry={nodes.Cylinder003_0.geometry} material={materials.Root} />
            </group>
            <group name="Cylinder002" position={[-3.46, 10.716, 0.944]} rotation={[-Math.PI, 1.452, -Math.PI]} scale={[0.002, 0.002, 0.017]}>
              <mesh name="Cylinder002_0" geometry={nodes.Cylinder002_0.geometry} material={materials.Root} />
            </group>
            <group name="Cylinder001" position={[-3.458, 10.716, 0.957]} rotation={[-Math.PI, 1.451, -Math.PI]} scale={[0.006, 0.006, 0.02]}>
              <mesh name="Cylinder001_0" geometry={nodes.Cylinder001_0.geometry} material={materials.Root} />
            </group>
            <group name="Cylinder" position={[-3.474, 10.638, 0.777]} rotation={[0, 0.383, 0]} scale={0.04}>
              <mesh name="Cylinder_0" geometry={nodes.Cylinder_0.geometry} material={materials.chromme_warna_silver} />
              <mesh name="Cylinder_1" geometry={nodes.Cylinder_1.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Circle003" position={[-1.994, 10.713, 1.291]} rotation={[0, 0.348, 0]} scale={0.031}>
              <mesh name="Circle003_0" geometry={nodes.Circle003_0.geometry} material={materials.Warna_Ban} />
            </group>
            <group name="Circle001" position={[-1.433, 10.684, 0.102]} rotation={[-Math.PI / 2, 0, 2.903]} scale={[0.736, 0.736, 0.394]}>
              <mesh name="Circle001_0" geometry={nodes.Circle001_0.geometry} material={materials.Warna_Ban} />
              <mesh name="Circle001_1" geometry={nodes.Circle001_1.geometry} material={materials['Material.004']} />
            </group>
            <group name="Circle" position={[-3.889, 10.684, 0.038]} rotation={[-Math.PI / 2, 0, 2.903]} scale={[0.736, 0.736, 0.394]}>
              <mesh name="Circle_0" geometry={nodes.Circle_0.geometry} material={materials.Warna_Ban} />
              <mesh name="Circle_1" geometry={nodes.Circle_1.geometry} material={materials['Material.004']} />
            </group>
            <group name="aksesoris_rangka_spedah001" position={[-1.714, 10.892, 0.632]} rotation={[0, -0.607, 0]} scale={0.009}>
              <mesh name="aksesoris_rangka_spedah001_0" geometry={nodes.aksesoris_rangka_spedah001_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="aksesoris_rangka_spedah" position={[-1.757, 10.712, 0.584]} rotation={[0, -0.607, 0]} scale={0.009}>
              <mesh name="aksesoris_rangka_spedah_0" geometry={nodes.aksesoris_rangka_spedah_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Lamp" position={[0.087, 1.005, 6.325]} rotation={[-0.268, 0.602, 1.931]}>
              <group name="Lamp_1" />
            </group>
            <group name="Cube" position={[-1.467, 10.525, 0.734]} rotation={[0, -0.024, 0]} scale={[0.315, 0.113, 0.203]}>
              <mesh name="Cube_0" geometry={nodes.Cube_0.geometry} material={materials.coklat} />
              <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.chromme_warna_silver} />
              <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Warna_Ban.001']} />
              <mesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials['Material.002']} />
            </group>
            <group name="Plane" position={[-1.411, 10.596, 0.719]} rotation={[0, -0.024, 0]}>
              <mesh name="Plane_0" geometry={nodes.Plane_0.geometry} material={materials.coklat} />
            </group>
            <group name="Cylinder007" position={[-3.183, 10.719, 1.053]} rotation={[-Math.PI, 1.481, -Math.PI]} scale={[0.039, 0.039, 0.012]}>
              <mesh name="Cylinder007_0" geometry={nodes.Cylinder007_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cylinder010" position={[-3.218, 10.719, 1.056]} rotation={[-Math.PI, 1.481, -Math.PI]} scale={[0.039, 0.039, 0.012]}>
              <mesh name="Cylinder010_0" geometry={nodes.Cylinder010_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cylinder011" position={[-2.235, 10.711, 1.403]} rotation={[-Math.PI / 2, 0, -0.024]} scale={0.022}>
              <mesh name="Cylinder011_0" geometry={nodes.Cylinder011_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cylinder012" position={[-2.736, 10.719, 1.011]} rotation={[-Math.PI, 1.481, -Math.PI]} scale={[0.039, 0.039, 0.012]}>
              <mesh name="Cylinder012_0" geometry={nodes.Cylinder012_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Plane003" position={[-1.505, 10.713, 0.988]} rotation={[0, -0.024, 0]} scale={[0.248, 0.065, 0.138]}>
              <mesh name="Plane003_0" geometry={nodes.Plane003_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cylinder014" position={[-1.484, 10.654, 0.996]} rotation={[-0.01, 1.542, -1.55]} scale={[0.009, 0.009, 0.05]}>
              <mesh name="Cylinder014_0" geometry={nodes.Cylinder014_0.geometry} material={materials.Root} />
            </group>
            <group name="Plane004" position={[-1.491, 10.71, 1.015]} rotation={[0, -0.024, 0]} scale={[0.408, 0.076, 0.313]}>
              <mesh name="Plane004_0" geometry={nodes.Plane004_0.geometry} material={materials.Root} />
            </group>
            <group name="Plane005" position={[-1.491, 10.71, 1.01]} rotation={[0, -0.024, 0]} scale={[0.408, 0.076, 0.313]}>
              <mesh name="Plane005_0" geometry={nodes.Plane005_0.geometry} material={materials.coklat} />
            </group>
            <group name="Cylinder015" position={[-2.433, 10.724, 0.014]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.061, 0.061, 0.086]}>
              <mesh name="Cylinder015_0" geometry={nodes.Cylinder015_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Cylinder013" position={[-1.939, 10.626, 0.059]} rotation={[0.572, 1.416, 2.487]} scale={[0.024, 0.025, 0.007]}>
              <mesh name="Cylinder013_0" geometry={nodes.Cylinder013_0.geometry} material={materials.Root} />
            </group>
            <group name="Cylinder016" position={[-1.694, 10.617, 0.081]} rotation={[0.758, 1.445, 2.22]} scale={[0.02, 0.02, 0.006]}>
              <mesh name="Cylinder016_0" geometry={nodes.Cylinder016_0.geometry} material={materials.Root} />
            </group>
            <group name="Circle002" position={[-2.566, 10.669, 0.904]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.023, 0.023, 0.132]}>
              <mesh name="Circle002_0" geometry={nodes.Circle002_0.geometry} material={materials.Root} />
            </group>
            <group name="Circle004" position={[-2.565, 10.758, 0.906]} rotation={[-Math.PI / 2, 0, -0.024]} scale={[0.023, 0.023, 0.132]}>
              <mesh name="Circle004_0" geometry={nodes.Circle004_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cube001" position={[-2.466, 10.715, 0.655]} rotation={[0, -0.024, 0]} scale={[0.416, 0.15, 0.268]}>
              <mesh name="Cube001_0" geometry={nodes.Cube001_0.geometry} material={materials.coklat} />
            </group>
            <group name="Plane006" position={[-2.118, 10.726, 0.692]} rotation={[-Math.PI / 2, 0, 0.341]} scale={0.206}>
              <mesh name="Plane006_0" geometry={nodes.Plane006_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Cylinder017" position={[-2.171, 10.719, 0.817]} rotation={[-Math.PI, -0.338, -Math.PI]} scale={[0.042, 0.043, 0.013]}>
              <mesh name="Cylinder017_0" geometry={nodes.Cylinder017_0.geometry} material={materials.coklat} />
            </group>
            <group name="Cylinder018" position={[-2.255, 10.719, 0.579]} rotation={[-Math.PI, -0.338, -Math.PI]} scale={[0.042, 0.043, 0.013]}>
              <mesh name="Cylinder018_0" geometry={nodes.Cylinder018_0.geometry} material={materials.coklat} />
            </group>
            <group name="Cylinder019" position={[-3.549, 10.713, 1.171]} rotation={[0, 0.165, 0]} scale={0.056}>
              <mesh name="Cylinder019_0" geometry={nodes.Cylinder019_0.geometry} material={materials['chromme_warna_silver.001']} />
              <mesh name="Cylinder019_1" geometry={nodes.Cylinder019_1.geometry} material={materials.lampu} />
              <mesh name="Cylinder019_2" geometry={nodes.Cylinder019_2.geometry} material={materials['Material.004']} />
            </group>
            <group name="Cylinder020" position={[-3.644, 10.715, 1.181]} rotation={[0, -0.024, 0]} scale={[0.008, 0.008, 0.021]}>
              <mesh name="Cylinder020_0" geometry={nodes.Cylinder020_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cylinder021" position={[-3.338, 10.719, 1.149]} rotation={[-Math.PI, -0.323, -Math.PI]} scale={[0.059, 0.059, 0.018]}>
              <mesh name="Cylinder021_0" geometry={nodes.Cylinder021_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cube003" position={[-3.691, 10.798, 1.261]} rotation={[0, -0.024, 2.953]} scale={[0.315, 0.113, 0.203]}>
              <mesh name="Cube003_0" geometry={nodes.Cube003_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Plane007" position={[-1.372, 10.612, 0.175]} rotation={[0, -0.024, 0]}>
              <mesh name="Plane007_0" geometry={nodes.Plane007_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Plane008" position={[1.384, 10.682, 0.146]} rotation={[-Math.PI / 2, 0, 0]} scale={0.574}>
              <mesh name="Plane008_0" geometry={nodes.Plane008_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Circle005" position={[-2.427, 10.715, -0.059]} rotation={[0, -0.024, 0]} scale={[0.824, 0.64, 0.753]}>
              <mesh name="Circle005_0" geometry={nodes.Circle005_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cylinder022" position={[-0.656, 10.711, 0.393]} rotation={[0, 1.547, 0]} scale={[0.135, 0.135, 0.026]}>
              <mesh name="Cylinder022_0" geometry={nodes.Cylinder022_0.geometry} material={materials['chromme_warna_silver.001']} />
              <mesh name="Cylinder022_1" geometry={nodes.Cylinder022_1.geometry} material={materials['Material.003']} />
            </group>
            <group name="Plane009" position={[-3.558, 11.767, 0.727]} rotation={[0, 1.547, 0]} scale={[0.055, 0.098, 0.098]}>
              <mesh name="Plane009_0" geometry={nodes.Plane009_0.geometry} material={materials.Material} />
              <mesh name="Plane009_1" geometry={nodes.Plane009_1.geometry} material={materials.lampu} />
            </group>
            <group name="Cylinder023" position={[-3.316, 10.717, 1.492]} rotation={[-Math.PI / 2, 0, -0.024]} scale={0.024}>
              <mesh name="Cylinder023_0" geometry={nodes.Cylinder023_0.geometry} material={materials['Material.004']} />
              <mesh name="Cylinder023_1" geometry={nodes.Cylinder023_1.geometry} material={materials['Material.002']} />
            </group>
            <group name="Cylinder024" position={[-1.587, 10.565, 0.095]} rotation={[3.131, -1.47, 3.131]} scale={[0.011, 0.011, 0.362]}>
              <mesh name="Cylinder024_0" geometry={nodes.Cylinder024_0.geometry} material={materials.Root} />
            </group>
            <group name="Cylinder025" position={[-3.329, 10.717, 1.469]} rotation={[-1.571, 0, 0.335]} scale={[0.011, 0.008, 0.016]}>
              <mesh name="Cylinder025_0" geometry={nodes.Cylinder025_0.geometry} material={materials['Material.004']} />
              <mesh name="Cylinder025_1" geometry={nodes.Cylinder025_1.geometry} material={materials['Material.002']} />
            </group>
            <group name="Cylinder027" position={[-2.736, 10.719, 1.011]} rotation={[-Math.PI, 1.481, -Math.PI]} scale={[0.039, 0.039, 0.012]}>
              <mesh name="Cylinder027_0" geometry={nodes.Cylinder027_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Plane010" position={[-3.095, 10.141, 1.613]} rotation={[1.128, -0.802, 2.712]} scale={[0.23, 0.167, 0.173]}>
              <mesh name="Plane010_0" geometry={nodes.Plane010_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Plane012" position={[-1.419, 10.705, 0.106]} rotation={[0, 1.525, 0]} scale={[0.403, 0.42, 0.403]}>
              <mesh name="Plane012_0" geometry={nodes.Plane012_0.geometry} material={materials['Material.004']} />
            </group>
            <group name="Plane013" position={[-1.789, 10.709, 0.739]} rotation={[0, -1.263, -Math.PI / 2]} scale={0.486}>
              <mesh name="Plane013_0" geometry={nodes.Plane013_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Bolt" position={[-1.889, 10.702, 0.805]} rotation={[0, 0.872, 0]} scale={0.03}>
              <mesh name="Bolt_0" geometry={nodes.Bolt_0.geometry} material={materials.Root} />
            </group>
            <group name="Cube004" position={[-1.852, 9.964, 0.81]} rotation={[0, -0.181, 0]} scale={0.016}>
              <mesh name="Cube004_0" geometry={nodes.Cube004_0.geometry} material={materials.Root} />
            </group>
            <group name="Cube005" position={[-3.523, 10.021, 0.77]} rotation={[0, 0.911, 0]} scale={[0.017, 0.014, 0.017]}>
              <mesh name="Cube005_0" geometry={nodes.Cube005_0.geometry} material={materials.Root} />
            </group>
            <group name="Bolt001" position={[-3.546, 10.708, 0.802]} rotation={[-Math.PI, 1.177, -Math.PI]} scale={[0.032, 0.028, 0.032]}>
              <mesh name="Bolt001_0" geometry={nodes.Bolt001_0.geometry} material={materials.Root} />
            </group>
            <group name="Plane014" position={[-3.559, 10.715, 0.676]} rotation={[0, -0.17, -Math.PI / 2]} scale={[0.452, 0.517, 0.517]}>
              <mesh name="Plane014_0" geometry={nodes.Plane014_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="Cylinder026" position={[-3.608, 10.635, 0.659]} rotation={[0, 0.408, 0]} scale={0.014}>
              <mesh name="Cylinder026_0" geometry={nodes.Cylinder026_0.geometry} material={materials['chromme_warna_silver.001']} />
            </group>
            <group name="aksesoris_rangka_spedah002" position={[-1.757, 10.712, 0.584]} rotation={[0, -0.607, 0]} scale={0.009}>
              <mesh name="aksesoris_rangka_spedah002_0" geometry={nodes.aksesoris_rangka_spedah002_0.geometry} material={materials.chromme_warna_silver} />
            </group>
            <group name="Cylinder028" position={[-2.488, 10.731, -0.856]} scale={[2.565, 2.565, 0.15]}>
              <mesh name="Cylinder028_0" geometry={nodes.Cylinder028_0.geometry} material={materials.Root} />
            </group>
            <group name="Plane015" position={[-3.477, 10.716, 0.955]} rotation={[0, Math.PI / 2, 0]} scale={0.028}>
              <mesh name="Plane015_0" geometry={nodes.Plane015_0.geometry} material={materials.Root} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
